### ISSUE TITLE
pytorch version 

### ISSUE THREAD

**Issue by ZhangJT0127** [fitushar/3D-GuidedGradCAM-for-Medical-Imaging#2]
hello! can you give a pytorch version?

**Comment by fitushar** [comment]
Sorry, I have minimal expertise over PyTorch. Hopefully, you will be able to find some open-source implementation online.

**Comment by ZhangJT0127** [comment]
> Sorry, I have minimal expertise over PyTorch. Hopefully, you will be able to find some open-source implementation online.



> Sorry, I have minimal expertise over PyTorch. Hopefully, you will be able to find some open-source implementation online.

ok, thank you.

**Comment by caixh39** [comment]
> > Sorry, I have minimal expertise over PyTorch. Hopefully, you will be able to find some open-source implementation online.
> 
> > Sorry, I have minimal expertise over PyTorch. Hopefully, you will be able to find some open-source implementation online.
> 
> ok, thank you.

hi, have you find open-source pytorch version for MRI image?

**Comment by zsddd** [comment]
> hi, have you find open-source pytorch version

hi, have you find open-source pytorch version？
