### ISSUE TITLE
About dataset, pre trained weights and sample images.

### ISSUE THREAD

**Issue by Ljiaqii** [fitushar/3D-GuidedGradCAM-for-Medical-Imaging#3]
Hi! Thanks for sharing your great work! Now I want to train the model. Could you please provide me with some examples for program operation? Includes pretrained weights and sample images. In addition, could you please provide relevant datasets? Thank you very much and look forward to your reply!

**Comment by fitushar** [comment]
Please check out this two repos as reference: 
1. https://github.com/fitushar/multi-label-weakly-supervised-classification-of-body-ct
2. https://github.com/fitushar/3D-Medical-Imaging-Preprocessing-All-you-need
